/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.soundpaint;

import org.junit.jupiter.api.Test;
import org.soundpaint.rp2040pio.SingleApp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SingleApp classUnderTest = new SingleApp();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
